// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQDzzdjZMcARtxOqtaCxXwKQSP5fVqknk',
    appId: '1:58008619754:web:08a9067c35db411dd8e593',
    messagingSenderId: '58008619754',
    projectId: 'pmw-studybuddy-2026',
    authDomain: 'pmw-studybuddy-2026.firebaseapp.com',
    storageBucket: 'pmw-studybuddy-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD42RpoII9UMQ-oVik45IwSkRmb6Di1SYA',
    appId: '1:58008619754:android:ac1aea244a6eac98d8e593',
    messagingSenderId: '58008619754',
    projectId: 'pmw-studybuddy-2026',
    storageBucket: 'pmw-studybuddy-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsr_oCKvRpiDjj1XxJJrpT-j8RKSn8pMM',
    appId: '1:58008619754:ios:3d1ed6e07a62f684d8e593',
    messagingSenderId: '58008619754',
    projectId: 'pmw-studybuddy-2026',
    storageBucket: 'pmw-studybuddy-2026.firebasestorage.app',
    iosBundleId: 'com.example.studybuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsr_oCKvRpiDjj1XxJJrpT-j8RKSn8pMM',
    appId: '1:58008619754:ios:3d1ed6e07a62f684d8e593',
    messagingSenderId: '58008619754',
    projectId: 'pmw-studybuddy-2026',
    storageBucket: 'pmw-studybuddy-2026.firebasestorage.app',
    iosBundleId: 'com.example.studybuddy',
  );
}
